language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
# command to install dependencies
install:
  - "sudo pip install ."
  - "sudo pip install -r requirements.txt"
# command to run tests
script: python setup.py test
